### ISSUE TITLE
edit batch issue

### ISSUE THREAD

**Issue by jingda123** [revaturelabs/assignforce-client#244] opened 2018-07-17 17:20 UTC
The main problem is when you switch to edit batches through the pen icon in batch tab, the way they coded it, it will automatically populate the edit batch section input with information from batch you are editing. However, they coded it wrongly, therefore trainer input, skill input are not getting populated, and are not clickable to change

**Comment by mfboulos** [comment] 2018-07-17 18:06
Closing this issue as a duplicate of #239

**Closed by mfboulos** 2018-07-17 18:06 UTC
Labels: duplicate
