### ISSUE TITLE
Trainer permissions need to be changed

### ISSUE THREAD

**Issue by Falco830** [revaturelabs/assignforce-client#210] opened 2018-07-10 17:49 UTC
A trainer should not be able to alter: 

- addresses
- batches
- curricula
- skills
- other trainers
- their own active status

**Comment by mfboulos** [comment] 2018-07-17 15:04
Adding this description to issue #211 to compile all trainer permission related issues into a single issue, marked as duplicate of #211.

**Closed** 2018-07-17 15:06 UTC
Labels: duplicate
